# Generated by Django 2.2.5 on 2019-11-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='sal',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
